//Created using eclipse WindowBuilder
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Font;

import javax.swing.JPanel;

import java.awt.Dimension;
import javax.swing.JTextArea;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class gui_program extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form gui_program
     */
    public gui_program() {
		setResizable(false);
		setIconImage(Toolkit.getDefaultToolkit().getImage(gui_program.class.getResource("/com/sun/java/swing/plaf/windows/icons/Computer.gif")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setPreferredSize(new Dimension(379, 365));
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
					jButton1ActionPerformed(evt);
				
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Browse for The Text File");

        jButton2.setText("Cancel");
        jButton2.setActionCommand("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Locality Sensitive Hashing");

        jLabel5.setText("Selected File:");

        jButton3.setText("Run");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
    
					try {
						jButton3ActionPerformed(evt);
					} catch (FileNotFoundException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (UnsupportedEncodingException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				
            }
        });
        jTextPane2 = new javax.swing.JTextPane();
        jTextArea1 = new JTextArea();
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
        jTextArea1.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
    
        
        javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(48)
        			.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        			.addGap(36)
        			.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        			.addGap(37)
        			.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        			.addGap(46))
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTextPane2, GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(Alignment.LEADING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(295, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(208, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(187, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTextArea1, GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        			.addContainerGap())
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel3)
        			.addGap(13)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jTextPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton2)
        				.addComponent(jButton1)
        				.addComponent(jButton3))
        			.addGap(18)
        			.addComponent(jTextArea1, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(gl_jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>
    static String path;
    static String parent;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
    	 // TODO add your handling code here:
    	jButton3.setEnabled(true);
    	File chosenFile = null;
    	FileNameExtensionFilter ft = new FileNameExtensionFilter("Text Files", "txt");
        JFileChooser chooser= new JFileChooser(System.getProperty("user.dir"));
        chooser.addChoosableFileFilter(ft);
        int choice = chooser.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION){
        	chosenFile = chooser.getSelectedFile();
        }
        parent=chosenFile.getParent();
        path=chosenFile.getPath();
        jTextPane2.setText(path);
        jTextArea1.setText(collector.f_time);

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	System.exit(0);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException, UnsupportedEncodingException{
        String holder[]=null;
    	if(path!=null){
    		holder=collector.collect(path);
	        PrintWriter writer = new PrintWriter(parent+"/scs2009_sentences.txt", "UTF-8");
	        for(int i=0;i<holder.length;i++){
	        jTextArea1.append(holder[i]+" || ");
	        writer.println(holder[i]);
	        }
	    	writer.close();
	    	jButton3.setEnabled(false);
    	}
        
    	else{
    		JOptionPane.showMessageDialog(null, "Please Select a Text File");
    	}
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new gui_program().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane2;
    private JPanel jPanel1;
    
    
}
